export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SELECT_RESTART = 'SELECT_RESTART';
export const SELECT_START = 'SELECT_START';
export const GENRE_LIST = 'GENRE_LIST';
export const PREVIOUS_CATEGORY = 'PREVIOUS_CATEGORY';
export const FETCH_MAIN_FILM = 'FETCH_MAIN_FILM';
